import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "About Usage",
    description: "Generated by create next app",
};

export default function AboutLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section style={{background:'green'}}>
            <p>Navbar</p>
            {children}
        </section>
    );
}
